# Generated by Django 4.2.11 on 2026-03-26 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Askari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('department_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Roles', 'Default'), ('Operator', 'Operator'), ('Management', 'Management')], max_length=15)),
                ('office_location', models.CharField(choices=[('ARUSHA', 'ARUSHA BRANCH OFFICE'), ('DAR', 'DAR ES SALAAM HEAD OFFICE')], max_length=15)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DT1.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='example: uniform, silaha', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('UN AVAILABLE', 'AVAILABLE'), ('DEMAGED', 'DEMAGED'), ('MAINTAINANCE', 'MAINTAINANCE')], default='Available', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('director_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='DT1.directors')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DT1.supervisor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DT1.clientsite')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('askari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DT1.askari')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DT1.supervisor')),
                ('vifaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DT1.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='askari',
            name='current_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DT1.clientsite'),
        ),
        migrations.AddField(
            model_name='askari',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guards', to='DT1.supervisor'),
        ),
    ]
