# Generated by Django 4.2.11 on 2026-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('heading', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='updates/')),
            ],
        ),
    ]
