# Generated by Django 4.2.11 on 2026-03-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DT1', '0002_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='Title',
            new_name='title',
        ),
    ]
