# Generated by Django 4.2.11 on 2026-03-27 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DT1', '0003_rename_title_update_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
